### ISSUE TITLE
[Stability] Constantly crashing/offline, wont register.

### ISSUE THREAD

**Issue by NNickey** [Just-Some-Bots/ModTools#41] opened 2017-01-15 00:07 UTC
Gave the bot every single permission, and saw the bot post the 'join' message once I invited it
Said !!register, nothing happened
Went to Rh1n0-help on discord, and !!ping, no response..

Bot is heavily non functional/unstable.

**Comment by Yeehawlerz101** [comment] 2017-01-16 13:09
For me I have it so the bot role is just under the baby admin in my discord. So that the bat has power over everyone lower than itself.

**Comment by arunesh90** [comment] 2017-01-22 14:59
Closing as the issue as the bot was down at the time this issue was created and was also the cause of the issue.

**Closed by arunesh90** 2017-01-22 14:59 UTC
